src/Entity/File.php
<?php

namespace App\Entity;
use DateTime;
use JsonSerializable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File implements JsonSerializable
{
    public const TYPE_DOCUMENT = 1;
    public const TYPE_INVOICE = 2;
    public const TYPE_RECAP = 3;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Choice(callback="getTypes")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\File(mimeTypes={ "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.oasis.opendocument.spreadsheet", "application/vnd.oasis.opendocument.text", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })
     */
    private $drive_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $mime;
/**
     * @ORM\Column(type="datetime")
     */
    private $date;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Warrant", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $warrant;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Property", inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Invoice", mappedBy="file", cascade={"persist", "remove"})
     */
    private $invoice;

    /**
     * @ORM\OneToOne(targetEntity=Recap::class, mappedBy="file", cascade={"persist", "remove"})
     */
    private $recap;

    private $tmpName;

    public function __construct()
    {
        $this->setMime('application/pdf');
        $this->setDate(new DateTime());
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
    public function getDriveId()
    {
        return $this->drive_id;
    }

    public function setDriveId($drive_id): self
    {
        $this->drive_id = $drive_id;

        return $this;
    }

    public function getMime(): ?string
    {
        return $this->mime;
    }

    public function setMime(string $mime): self
    {
        $this->mime = $mime;

        return $this;
    }

    public function getWarrant(): ?Warrant
    {
        return $this->warrant;
    }

    public function setWarrant(?Warrant $warrant): self
    {
        $this->warrant = $warrant;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getTmpName(): ?string
    {
        return $this->tmpName;
    }

    public function setTmpName(string $tmpName): self
    {
        $this->tmpName = $tmpName;

        return $this;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(Invoice $invoice): self
    {
        $this->invoice = $invoice;

        // set the owning side of the relation if necessary
        if ($this !== $invoice->getFile()) {
            $invoice->setFile($this);
        }

        return $this;
    }

    public function getExtension(): string
    {
        switch ($this->getMime()) {
            case 'application/msword':
                return '.doc';
            case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
                return '.docx';
            case 'application/vnd.oasis.opendocument.spreadsheet':
                return '.ods';
            case 'application/vnd.oasis.opendocument.text':
                return '.odt';
            case 'application/vnd.ms-excel':
                return '.xsl';
            case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
                return '.xslx';
            case 'application/pdf':
            default:
                return '.pdf';
        }
    }

    public static function getTypes()
    {
        return [self::TYPE_DOCUMENT, self::TYPE_INVOICE];
    }

    public function getRecap(): ?Recap
    {
        return $this->recap;
    }

    public function setRecap(Recap $recap): self
    {
        // set the owning side of the relation if necessary
        if ($recap->getFile() !== $this) {
            $recap->setFile($this);
        }

        $this->recap = $recap;

        return $this;
    }

    public function jsonSerialize()
    {
        return array(
            'id' => $this->id,
            'drive_id' => $this->drive_id,
            'name' => $this->name,
            'mime' => $this->mime,
            'full_name' => $this->getName().$this->getExtension(),
        );
    }
}

src/Entity/Warrant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Bic;
use Symfony\Component\Validator\Constraints\Iban;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WarrantRepository")
 */
class Warrant
{
    public const TYPE_BUYERS = 1;
    public const TYPE_SELLERS = 2;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $client_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone1;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fact_address;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $fact_postal_code;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $fact_city;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $fact_country;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $bank_establishment_code;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $bank_code_box;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $bank_account_number;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $bank_key;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bank_domiciliation;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $bank_iban;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $bank_bic;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $bank_ics;
     /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $rum;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Property", mappedBy="warrant")
     */
    private $properties;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mail1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mail2;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="warrant")
     */
    private $files;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="warrants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creationUser;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $editionUser;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Mail", mappedBy="warrant")
     */
    private $mails;

    public function __construct()
    {
        $this->setActive(true);
        $this->setCountry('France');
        $this->properties = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->mails = new ArrayCollection();
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('firstname', new NotBlank());
        $metadata->addPropertyConstraint('lastname', new NotBlank());
        $metadata->addPropertyConstraint('address', new NotBlank());
        $metadata->addPropertyConstraints('postal_code', [new NotBlank(), new Length(["min" => 5, "max" => 5])]);
        $metadata->addPropertyConstraint('city', new NotBlank());
        $metadata->addPropertyConstraint('country', new NotBlank());
        $metadata->addPropertyConstraint('bank_iban', new Iban());
        $metadata->addPropertyConstraint('bank_bic', new Bic());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?string
    {
        return $this->client_id;
    }

    public function setClientId(string $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstName): self
    {
        $this->firstname = ucwords($firstName);

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastName): self
    {
        $this->lastname = ucwords($lastName);

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = ucwords($city);

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = ucwords($country);

        return $this;
    }

    public function getPhone1(): ?string
    {
        return $this->phone1;
    }

    public function setPhone1(?string $phone1): self
    {
        $this->phone1 = $phone1;

        return $this;
    }

    public function getPhone2(): ?string
    {
        return $this->phone2;
    }

    public function setPhone2(?string $phone2): self
    {
        $this->phone2 = $phone2;

        return $this;
    }

    public function getFactAddress(): ?string
    {
        return $this->fact_address;
    }

    public function setFactAddress(?string $fact_address): self
    {
        $this->fact_address = $fact_address;

        return $this;
    }

    public function getFactPostalCode(): ?string
    {
        return $this->fact_postal_code;
    }

    public function setFactPostalCode(?string $fact_postal_code): self
    {
        $this->fact_postal_code = $fact_postal_code;

        return $this;
    }

    public function getFactCity(): ?string
    {
        return $this->fact_city;
    }

    public function setFactCity(?string $fact_city): self
    {
        $this->fact_city = $fact_city;

        return $this;
    }

    public function getFactCountry(): ?string
    {
        return $this->fact_country;
    }

    public function setFactCountry(?string $fact_country): self
    {
        $this->fact_country = $fact_country;

        return $this;
    }

    public function getBankEstablishmentCode(): ?string
    {
        return $this->bank_establishment_code;
    }

    public function setBankEstablishmentCode(?string $bank_establishment_code): self
    {
        $this->bank_establishment_code = $bank_establishment_code;

        return $this;
    }

    public function getBankCodeBox(): ?string
    {
        return $this->bank_code_box;
    }

    public function setBankCodeBox(?string $bank_code_box): self
    {
        $this->bank_code_box = $bank_code_box;

        return $this;
    }

    public function getBankAccountNumber(): ?string
    {
        return $this->bank_account_number;
    }

    public function setBankAccountNumber(?string $bank_account_number): self
    {
        $this->bank_account_number = $bank_account_number;

        return $this;
    }

    public function getBankKey(): ?string
    {
        return $this->bank_key;
    }

    public function setBankKey(?string $bank_key): self
    {
        $this->bank_key = $bank_key;

        return $this;
    }

    public function getBankDomiciliation(): ?string
    {
        return $this->bank_domiciliation;
    }

    public function setBankDomiciliation(?string $bank_domiciliation): self
    {
        $this->bank_domiciliation = $bank_domiciliation;

        return $this;
    }

    public function getBankIban(): ?string
    {
        return $this->bank_iban;
    }

    public function setBankIban(?string $bank_iban): self
    {
        $this->bank_iban = $bank_iban;

        return $this;
    }

    public function getBankBic(): ?string
    {
        return $this->bank_bic;
    }

    public function setBankBic(?string $bank_bic): self
    {
        $this->bank_bic = $bank_bic;

        return $this;
    }

    public function getBankIcs(): ?string
    {
        return $this->bank_ics;
    }

    public function setrum(?string $rum): self
    {
        $this->rum = $rum;

        return $this;
    }

    public function getrum(): ?string
    {
        return $this->rum;
    }

    public function setBankIcs(?string $bank_ics): self
    {
        $this->bank_ics = $bank_ics;

templates/invoice/annuel.html.twig
{% extends 'layout.html.twig' %}
{% import "macros/forms.html.twig" as mforms %}

{% block title %}Viag2e | Facturation annuelle{% endblock %}

{% block body %}
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="{{ path('dashboard') }}" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Facturation annuelle</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Facturation annuelle
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                {{ form_start(form) }}
                    <div class="form-group row">
                        <div class="col-lg-6">
                            <label for="form-property" class="col-4 col-form-label">Propriété</label>
                            <div class="col-12">
                                <span class="m-switch m-switch--outline m-switch--icon m-switch--brand">
                                    <label>
                                        {{ form_widget(form.property, {'attr': {'class': 'form-control m-input'}, 'id': 'form-property', 'label': false}) }}
                                        <span></span>
                                    </label>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label for="form-target" class="col-4 col-form-label">Cible</label>
                            <div class="col-12">
                                <span class="m-switch m-switch--outline m-switch--icon m-switch--brand">
                                    <label>
                                        {{ form_widget(form.target, {'attr': {'class': 'form-control m-input'}, 'id': 'form-target', 'label': false}) }}
                                        <span></span>
                                    </label>
                                </span>
                            </div>
                        </div>
                    </div>  
                    {{ mforms.group(form.period, 'period', 'Période', form.email, 'email', 'Email') }}
                    {{ mforms.group(form.label, 'label', 'Label', form.reason, 'reason', 'Motif') }}
                    {{ mforms.group(form.amount, 'amount', 'Montant de la rente', form.montantht, 'montantht', 'Montant honoraires HT') }}

                    

                    <input class="btn btn-outline-success btn-block" type="submit" value="Générer" />
                    {{ form_rest(form) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}{% endblock %}

templates/invoice/export.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Viag2e | Export{% endblock %}

{% block body %}
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="{{ path('dashboard') }}" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Export</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Export comptable
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <form action="{{ path('invoice_accounting') }}" method="post">
                    <div class="form-group row">
                        <div class="col-lg-6">
                            <label>Type:</label>
                            <div class="m-radio-list">
                                <label class="m-radio m-radio--primary">
                                    <input type="radio" name="type" value="{{ constant('App\\Entity\\Warrant::TYPE_BUYERS') }}" checked> Acquéreurs
                                    <span></span>
                                </label>
                                <label class="m-radio m-radio--primary">
                                    <input type="radio" name="type" value="{{ constant('App\\Entity\\Warrant::TYPE_SELLERS') }}"> Vendeurs
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label class="col-xl-12 col-lg-12 col-form-label" for="form-dates">Dates:</label>
                            <div class="col-xl-12 col-lg-12">
                                <input type="text" class="form-control m-input" id="form-dates" name="range" />
                            </div>
                        </div>
                    </div>
                    <input class="btn btn-outline-success btn-block" type="submit" value="Télécharger" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $('input[name="range"]').daterangepicker({
            autoApply: true,
            startDate: moment().subtract(1, 'month').startOf('month').format('L'),
            endDate: moment().subtract(1, 'month').endOf('month').format('L'),
        });
    </script>
{% endblock %}

templates/invoice/treat.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Viag2e | Facturation{% endblock %}

{% block body %}
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="{{ path('dashboard') }}" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Facturation</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Liste des factures | <a href="{{ path('invoices') }}"><small><i>Voir toutes les factures</i></small></a>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-4">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input" placeholder="Recherche..." id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span><i class="la la-search"></i></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <table class="m-datatable-invoices" id="html_table" width="100%">
                    <thead>
                    <tr>
                        <th title="Date" data-field="Date">Date</th>
                        <th title="Number" data-field="Number">N°</th>
                        <th title="Type" data-field="Type">Type</th>
                        <th title="PropertyID" data-field="PropertyID">N° Prop</th>
                        <th title="ID" data-field="ID">ID Client</th>
                        <th title="CustomerID" data-field="CustomerID">N° Client</th>
                        <th title="Customer" data-field="Customer">Client</th>
                        <th title="Annuity" data-field="Annuity">Rente</th>
                        <th title="HonoraryRates" data-field="HonoraryRates">Honoraires</th>
                        <th title="Status" data-field="Status">Statut</th>
                        <th title="Resend" data-field="Resend"></th>
                        <th title="Download" data-field="Download"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for invoice in invoices %}
                        <tr>
                            <td>{{ invoice.date|date('d-m-Y H:i') }}</td>
                            <td>{{ invoice.formattednumber }}</td>
                            <td>{{ invoice.typestring }}</td>
                            <td>{{ invoice.property.id }}</td>
                            <td>{{ invoice.property.warrant.id }}</td>
                            <td>{{ invoice.property.warrant.clientId }}</td>
                            <td><a href="{{ path('warrant_view', {'type': invoice.property.warrant.typestring, 'warrantId': invoice.property.warrant.id}) }}">{{ invoice.property.warrant.firstname }} {{ invoice.property.warrant.lastname }}</a></td>
                            <td>{{ invoice.data.property.annuity|number_format(2, '.', ' ') }}</td>
                            <td>{{ invoice.data.property.honoraryRates|number_format(2, '.', ' ') }}</td>
                            <td>{% if invoice.type == constant('App\\Entity\\Invoice::TYPE_RECEIPT') or invoice.status >= constant('App\\Entity\\Invoice::STATUS_PAYED') %}<span class="{{ invoice.statusclass }}">{{ invoice.statusstring }}</span>{% else %}<a href="#" data-id="{{ invoice.id }}" data-number="{{ invoice.formattednumber }}" data-toggle="modal" data-target="#m_modal_invoice_status" class="invoice-status m--font-bold {{ invoice.statusclass }}">{{ invoice.statusstring }}</a>{% endif %}</td>
                            <td><a href="{{ path('invoice_resend', {'invoiceId': invoice.id}) }}"><i class="la la-envelope" title="Renvoyer"></i> Renvoyer</a></td>
                            <td><a href="{{ path('file_download', {'fileId': invoice.file.driveId}) }}" target="_blank"><i class="la la-cloud-download" title="Télécharger"></i> Télécharger</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="m_modal_invoice_status" tabindex="-1" role="dialog" aria-labelledby="invoice_status" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="invoice_status_h">Modification du status <span id="modal-title">-</span></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <b>ATTENTION:</b> La validation du paiement provoque la génération de la quittance et est irréversible.
                    <form action="{{ path('invoice_payed') }}?treat=1" method="post" id="payed-form"><input type="hidden" name="id" value="0" id="payment-form-id"></form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="button" class="btn btn-primary" id="validate-payment">Valider le paiement</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ encore_entry_script_tags('html-table.invoices_treat') }}
    <script type="text/javascript">
        $(function() {
            $('.invoice-status').click(function () {
                $('#payment-form-id').attr('value', $(this).attr('data-id'));
                $('#modal-title').html($(this).attr('data-number'));
            });

            $('#validate-payment').click(function () {
                $('#payed-form').submit();
                $('#payment-form-id').attr('value', 0);
            });
        });
    </script>
{% endblock %}