src/Entity/BankExport.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BankExportRepository")
 */
class BankExport
{
    public const TYPE_AUTO = 1;
    public const TYPE_MANUAL = 2;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     */
    private $message_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $period;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Choice(callback="getTypes")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $drive_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __construct()
    {
        $this->setDate(new \DateTime());
        $this->setMessageId(md5(random_bytes(12)));
        $this->setType(self::TYPE_AUTO);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessageId(): ?string
    {
        return $this->message_id;
    }

    public function setMessageId(string $message_id): self
    {
        $this->message_id = $message_id;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function getTypeString(): ?string
    {
        return ($this->type === self::TYPE_AUTO) ? 'Automatique' : 'Manuel';
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDriveId(): ?string
    {
        return $this->drive_id;
    }

    public function setDriveId(string $drive_id): self
    {
        $this->drive_id = $drive_id;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getName(): string
    {
        return 'Export ' . str_replace('/', '-', $this->getPeriod()) . '.xml';
    }

    public static function getTypes()
    {
        return [self::TYPE_AUTO, self::TYPE_MANUAL];
    }
}

src/Entity/File.php
<?php

namespace App\Entity;
use DateTime;
use JsonSerializable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File implements JsonSerializable
{
    public const TYPE_DOCUMENT = 1;
    public const TYPE_INVOICE = 2;
    public const TYPE_RECAP = 3;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Choice(callback="getTypes")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\File(mimeTypes={ "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.oasis.opendocument.spreadsheet", "application/vnd.oasis.opendocument.text", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })
     */
    private $drive_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $mime;
/**
     * @ORM\Column(type="datetime")
     */
    private $date;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Warrant", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $warrant;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Property", inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Invoice", mappedBy="file", cascade={"persist", "remove"})
     */
    private $invoice;

    /**
     * @ORM\OneToOne(targetEntity=Recap::class, mappedBy="file", cascade={"persist", "remove"})
     */
    private $recap;

    private $tmpName;

    public function __construct()
    {
        $this->setMime('application/pdf');
        $this->setDate(new DateTime());
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
    public function getDriveId()
    {
        return $this->drive_id;
    }

    public function setDriveId($drive_id): self
    {
        $this->drive_id = $drive_id;

        return $this;
    }

    public function getMime(): ?string
    {
        return $this->mime;
    }

    public function setMime(string $mime): self
    {
        $this->mime = $mime;

        return $this;
    }

    public function getWarrant(): ?Warrant
    {
        return $this->warrant;
    }

    public function setWarrant(?Warrant $warrant): self
    {
        $this->warrant = $warrant;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getTmpName(): ?string
    {
        return $this->tmpName;
    }

    public function setTmpName(string $tmpName): self
    {
        $this->tmpName = $tmpName;

        return $this;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(Invoice $invoice): self
    {
        $this->invoice = $invoice;

        // set the owning side of the relation if necessary
        if ($this !== $invoice->getFile()) {
            $invoice->setFile($this);
        }

        return $this;
    }

    public function getExtension(): string
    {
        switch ($this->getMime()) {
            case 'application/msword':
                return '.doc';
            case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
                return '.docx';
            case 'application/vnd.oasis.opendocument.spreadsheet':
                return '.ods';
            case 'application/vnd.oasis.opendocument.text':
                return '.odt';
            case 'application/vnd.ms-excel':
                return '.xsl';
            case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
                return '.xslx';
            case 'application/pdf':
            default:
                return '.pdf';
        }
    }

    public static function getTypes()
    {
        return [self::TYPE_DOCUMENT, self::TYPE_INVOICE];
    }

    public function getRecap(): ?Recap
    {
        return $this->recap;
    }

    public function setRecap(Recap $recap): self
    {
        // set the owning side of the relation if necessary
        if ($recap->getFile() !== $this) {
            $recap->setFile($this);
        }

        $this->recap = $recap;

        return $this;
    }

    public function jsonSerialize()
    {
        return array(
            'id' => $this->id,
            'drive_id' => $this->drive_id,
            'name' => $this->name,
            'mime' => $this->mime,
            'full_name' => $this->getName().$this->getExtension(),
        );
    }
}

src/Controller/BankController.php
<?php

namespace App\Controller;

use App\Service\DriveManager;
use DateTime;
use App\Entity\BankExport;
use App\Service\Bank;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\HeaderUtils;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class BankController extends AbstractController
{
    /**
     * @Route("/bank/exports", name="bank_exports")
     *
     * @return Response
     */
    public function index()
    {
        $exports = $this->getDoctrine()->getManager()
            ->getRepository(BankExport::class)
            ->findAllOrdered();

        return $this->render('bank/index.html.twig', [
            'exports' => $exports,
        ]);
    }

    /**
     * @Route("/bank/generate", name="bank_generate", methods={"POST"})
     *
     * @param Request $request
     * @return Response
     *
     * @throws \Exception
     */
    public function generateBankFile(Request $request, DriveManager $drive)
    {
        $range = $request->get('range');

        if (empty($range)) {
            throw new BadRequestHttpException('Missing parameter');
        }

        $dates = explode(' - ', $range);
        if (count($dates) != 2) {
            throw new NotFoundHttpException('Invalid range');
        }

        $start = DateTime::createFromFormat('d/m/Y', $dates[0]);
        $end = DateTime::createFromFormat('d/m/Y', $dates[1]);

        if ($start === false || $end === false) {
            throw new NotFoundHttpException('Invalid range');
        }

        $bank = new Bank($this->container);
        $export = new BankExport();

        $xml = $bank->generate($start, $end, $export->getMessageId());

        $export->setDate(new DateTime());
        $export->setPeriod($range);
        $export->setType(BankExport::TYPE_MANUAL);
        $manager = $this->getDoctrine()->getManager();
        $manager->persist($export);


        if($this->getParameter('kernel.environment') != 'prod' || true) { // Tmp GDrive fix
            $export->setDriveId('notstored');
            $manager->flush();

            $response = new Response($xml);
            $disposition = HeaderUtils::makeDisposition(
                HeaderUtils::DISPOSITION_ATTACHMENT,
                'export_'. date('d-m-Y') .'.xml'
            );
            $response->headers->set('Content-Disposition', $disposition);
            return $response;
        }

        $export->setDriveId($drive->addExport($export->getName(), $xml));
        $manager->flush();

        return $this->redirectToRoute('file_export_download', ['fileId' => $export->getDriveId()]);
    }


    /**
     * @Route("/bank/generate_fa", name="bank_generate_fa", methods={"POST"})
     *
     * @param Request $request
     * @return Response
     *
     * @throws \Exception
     */
    public function generateFABankFile(Request $request, DriveManager $drive)
    {
        $range = $request->get('range');

        if (empty($range)) {
            throw new BadRequestHttpException('Missing parameter');
        }

        $dates = explode(' - ', $range);
        if (count($dates) != 2) {
            throw new NotFoundHttpException('Invalid range');
        }

        $start = DateTime::createFromFormat('d/m/Y', $dates[0]);
        $end = DateTime::createFromFormat('d/m/Y', $dates[1]);

        if ($start === false || $end === false) {
            throw new NotFoundHttpException('Invalid range');
        }

        $bank = new Bank($this->container);
        $export = new BankExport();

        $xml = $bank->generate_fa($start, $end, $export->getMessageId());

        $export->setDate(new DateTime());
        $export->setPeriod($range);
        $export->setType(BankExport::TYPE_MANUAL);
        $manager = $this->getDoctrine()->getManager();
        $manager->persist($export);


        if($this->getParameter('kernel.environment') != 'prod' || true) { // Tmp GDrive fix
            $export->setDriveId('notstored');
            $manager->flush();

            $response = new Response($xml);
            $disposition = HeaderUtils::makeDisposition(
                HeaderUtils::DISPOSITION_ATTACHMENT,
                'export_'. date('d-m-Y') .'.xml'
            );
            $response->headers->set('Content-Disposition', $disposition);
            return $response;
        }

        $export->setDriveId($drive->addExport($export->getName(), $xml));
        $manager->flush();

        return $this->redirectToRoute('file_export_download', ['fileId' => $export->getDriveId()]);
    }
}

templates/bank/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Viag2e | Exports banque{% endblock %}

{% block body %}
    <div class="m-subheader">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="{{ path('dashboard') }}" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Exports banque</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Liste des exports
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-6 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-5">
                                    <div class="m-form__group m-form__group--inline">
                                        <div class="m-form__label">
                                            <label class="m-label m-label--single" for="m_form_type">Type:</label>
                                        </div>
                                        <div class="m-form__control">
                                            <select class="form-control m-bootstrap-select" id="m_form_type">
                                                <option value="">Tous</option>
                                                <option value="Automatique">Automatique</option>
                                                <option value="Manuel">Manuel</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="d-md-none m--margin-bottom-10"></div>
                                </div>
                                <div class="col-md-6">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input" placeholder="Recherche..." id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span><i class="la la-search"></i></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 order-1 order-xl-2 m--align-right">
                            <button type="button" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill" data-toggle="modal" data-target="#m_modal_generate_fa" id="btn-modal-generate-fa">
                                        <span>
                                            <i class="la la-code"></i>
                                            <span>Génération manuelle FA</span>
                                        </span>
                            </button>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                        <div class="col-xl-3 order-1 order-xl-2 m--align-right">
                            <button type="button" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill" data-toggle="modal" data-target="#m_modal_generate" id="btn-modal-generate">
                                        <span>
                                            <i class="la la-code"></i>
                                            <span>Génération manuelle</span>
                                        </span>
                            </button>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <table class="m-datatable-exports" id="html_table" width="100%">
                    <thead>
                    <tr>
                        <th title="Période" data-field="Période">Période</th>
                        <th title="ID" data-field="ID">ID</th>
                        <th title="Type" data-field="Type">Type</th>
                        <th title="Date" data-field="Date">Date</th>
                        <th title="Download" data-field="Download"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for export in exports %}
                        <tr>
                            <td>{{ export.period }}</td>
                            <td>{{ export.messageId }}</td>
                            <td>{{ export.typestring }}</td>
                            <td>{{ export.date|date('d-m-Y H:i') }}</td>
                            <td>{% if export.driveId == 'notstored' %}-{% else %}<a href="{{ path('file_export_download', {'fileId': export.driveId}) }}" target="_blank"><i class="la la-cloud-download" title="Télécharger"></i> Télécharger</a>{% endif %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="m_modal_generate" tabindex="-1" role="dialog" aria-labelledby="generate" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Génération manuelle</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ path('bank_generate') }}" method="post" id="generate-form">
                        <label class="col-xl-12 col-lg-12 col-form-label" for="form-dates">Dates:</label>
                        <div class="col-xl-12 col-lg-12">
                            <input type="text" class="form-control m-input" id="form-dates" name="range" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="button" class="btn btn-primary" id="generate-button">Générer</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="m_modal_generate_fa" tabindex="-1" role="dialog" aria-labelledby="generate" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Génération manuelle FA</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ path('bank_generate_fa') }}" method="post" id="generate-form-fa">
                        <label class="col-xl-12 col-lg-12 col-form-label" for="form-dates">Dates:</label>
                        <div class="col-xl-12 col-lg-12">
                            <input type="text" class="form-control m-input" id="form-dates" name="range" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="button" class="btn btn-primary" id="generate-button-fa">Générer</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ encore_entry_script_tags('html-table.bank') }}
    <script type="text/javascript">
        $('input[name="range"]').daterangepicker({
            autoApply: true,
            startDate: moment().subtract(1, 'month').startOf('month').format('L'),
            endDate: moment().subtract(1, 'month').endOf('month').format('L'),
        });

        $('#generate-button').click(function () {
            $('#generate-form').submit();
        });
        $('#generate-button-fa').click(function () {
            $('#generate-form-fa').submit();
        });
    </script>
{% endblock %}